export const COMPETENCES = [
  {
    unitName: 'Java',
    competence: [
      {
        id: 'competence1',
        value: 'cloud computing',
        name: 'Cloud computing',
        presenter: 'Frits',
        content: 'test',
        class: 'competence-card-container--blue',
        url: "infopage?unit=Java&competence=Cloud computing",
      },
      {
        id: 'competence2',
        value: 'cloud startup',
        name: 'Cloud startup',
        presenter: 'Frits',
        content: 'test',
        class: 'competence-card-container--blue',
        url: "infopage?unit=Java&competence=Cloud startup",
      },
      {
        id: 'competence3',
        value: 'cloud',
        name: 'Cloud',
        presenter: 'Mark',
        content: 'test',
        class: 'competence-card-container--blue',
        url: "infopage?unit=Java&competence=Cloud",
      },
    ],
  },
  {
    unitName: '.NET',
    competence: [
      {
        id: 'competence1',
        value: 'mock name',
        name: 'Mock name',
        presenter: 'Mock presenter',
        content: 'Mock content',
        class: 'competence-card-container--blue',
        url: "infopage?unit=Java&competence=Mock name",
      },
      {
        id: 'competence2',
        value: 'mock name',
        name: 'Mock name',
        presenter: 'Mock presenter',
        content: 'Mock content',
        class: 'competence-card-container--blue',
        url: "infopage?unit=Java&competence=Mock name",
      },
    ],
  },
  {
    unitName: 'Testing',
    competence: [
      {
        id: 'competence1',
        value: 'mock name',
        name: 'Mock name',
        presenter: 'Mock presenter',
        content: 'Mock content',
        class: 'competence-card-container--green',
        url: "infopage?unit=Java&competence=Mock name",
      },
      {
        id: 'competence2',
        value: 'mock name',
        name: 'Mock name',
        presenter: 'Mock presenter',
        content: 'Mock content',
        class: 'competence-card-container--green',
        url: "infopage?unit=Java&competence=Mock name",
      },
    ],
  },
  {
    unitName: 'Low Coding',
    competence: [
      {
        id: 'competence1',
        value: 'mock name',
        name: 'Mock name',
        presenter: 'Mock presenter',
        content: 'Mock content',
        class: 'competence-card-container--green',
        url: "infopage?unit=Java&competence=Mock name",
      },
      {
        id: 'competence2',
        value: 'mock name',
        name: 'Mock name',
        presenter: 'Mock presenter',
        content: 'Mock content',
        class: 'competence-card-container--green',
        url: "infopage?unit=Java&competence=Mock name",
      },
    ],
  },
  {
    unitName: 'Business Analyse',
    competence: [
      {
        id: 'competence1',
        value: 'mock name',
        name: 'Mock name',
        presenter: 'Mock presenter',
        content: 'Mock content',
        class: 'competence-card-container--purple',
        url: "infopage?unit=Java&competence=Mock name",
      },
      {
        id: 'competence2',
        value: 'mock name',
        name: 'Mock name',
        presenter: 'Mock presenter',
        content: 'Mock content',
        class: 'competence-card-container--purple',
        url: "infopage?unit=Java&competence=Mock name",
      },
    ],
  },
  {
    unitName: 'Oracle',
    competence: [
      {
        id: 'competence1',
        value: 'mock name',
        name: 'Mock name',
        presenter: 'Mock presenter',
        content: 'Mock content',
        class: 'competence-card-container--purple',
        url: "infopage?unit=Java&competence=Mock name",
      },
      {
        id: 'competence2',
        value: 'mock name',
        name: 'Mock name',
        presenter: 'Mock presenter',
        content: 'Mock content',
        class: 'competence-card-container--purple',
        url: "infopage?unit=Java&competence=Mock name",
      },
    ],
  },
  {
    unitName: 'Cloud',
    competence: [
      {
        id: 'competence1',
        value: 'mock name',
        name: 'Mock name',
        presenter: 'Mock presenter',
        content: 'Mock content',
        class: 'competence-card-container--red',
        url: "infopage?unit=Java&competence=Mock name",
      },
      {
        id: 'competence2',
        value: 'mock name',
        name: 'Mock name',
        presenter: 'Mock presenter',
        content: 'Mock content',
        class: 'competence-card-container--red',
        url: "infopage?unit=Java&competence=Mock name",
      },
    ],
  },
  {
    unitName: 'Agile',
    competence: [
      {
        id: 'competence1',
        value: 'mock name',
        name: 'Mock name',
        presenter: 'Mock presenter',
        content: 'Mock content',
        class: 'competence-card-container--red',
        url: "infopage?unit=Java&competence=Mock name",
      },
      {
        id: 'competence2',
        value: 'mock name',
        name: 'Mock name',
        presenter: 'Mock presenter',
        content: 'Mock content',
        class: 'competence-card-container--red',
        url: "infopage?unit=Java&competence=Mock name",
      },
    ],
  },
];
