export const UNITS = [
  {
    id: 'unit1',
    value: 'java',
    name: 'Java',
    content: 'test',
    class: 'unit-card-container--blue',
    isFavorite: false,
    url: "competence?unit=Java",
  },
  {
    id: 'unit2',
    value: '.net',
    name: '.NET',
    content: 'test',
    class: 'unit-card-container--blue',
    isFavorite: false,
    url: "competence?unit=.NET",
  },
  {
    id: 'unit3',
    value: 'testing',
    name: 'Testing',
    content: 'test',
    class: 'unit-card-container--green',
    isFavorite: false,
    url: "competence?unit=Testing",
  },
  {
    id: 'unit4',
    value: 'low coding',
    name: 'Low Coding',
    content: 'test',
    class: 'unit-card-container--green',
    isFavorite: false,
    url: "competence?unit=Low Coding",
  },
  {
    id: 'unit5',
    value: 'business analyse',
    name: 'Business Analyse',
    content: 'test',
    class: 'unit-card-container--purple',
    isFavorite: false,
    url: "competence?unit=Business Analyse",
  },
  {
    id: 'unit6',
    value: 'oracle',
    name: 'Oracle',
    content: 'test',
    class: 'unit-card-container--purple',
    isFavorite: false,
    url: "competence?unit=Oracle",
  },
  {
    id: 'unit7',
    value: 'cloud',
    name: 'Cloud',
    content: 'test',
    class: 'unit-card-container--red',
    isFavorite: false,
    url: "competence?unit=Cloud",
  },
  {
    id: 'unit8',
    value: 'agile',
    name: 'Agile',
    content: 'test',
    class: 'unit-card-container--red',
    isFavorite: false,
    url: "competence?unit=Agile",
  },
];
